// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SupportGestor.Data;

#nullable disable

namespace SupportGestor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SupportGestor.Models.AtendimentoModel", b =>
                {
                    b.Property<int>("AtendimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AtendimentoId"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataAtendimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NivelDificuldade")
                        .HasColumnType("integer");

                    b.Property<string>("NomeAtendente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotasAtendimento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Problema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AtendimentoId");

                    b.ToTable("atendimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
